app/urls.py
from django.urls import path
from .views import teacherregister,studentregister,login_view,logout
from . import views
from .views import (
ClassroomCreateView,ClassroomListView,ClassroomDetailView,ClassroomUpdateView,ClassroomDeleteView,
SubjectCreateView,SubjectListView,SubjectDetailView,SubjectUpdateView,SubjectDeleteView,
ClassMemberCreateView,ClassMemberListView,ClassMemberDetailView,ClassMemberUpdateView,ClassMemberDeleteView,
TimetableCreateView,TimetableListView,TimetableDetailView,TimetableUpdateView,TimetableDeleteView,CrudView,chatroom
)

urlpatterns = [
                path('', views.index, name='index'),
                path('health', views.health, name='health'),
                path('404', views.handler404, name='404'),
                path('500', views.handler500, name='500'),
                path('signup/teacher', teacherregister,name='register-teacher'),
                path('signup/student', studentregister,name='register-student'),
                path('accounts/login/', login_view, name='login'),
                path('logout/', logout,name='logout'),
                #Classroom
                path('classroom/new', ClassroomCreateView.as_view(),name='classroom-create'),
                path('classroom_list', ClassroomListView.as_view(),name='classroom-list'),
                path('classroom/<str:pk>/', ClassroomDetailView.as_view(),name='classroom-detail'),
                path('classroom/<str:pk>/update', ClassroomUpdateView.as_view(),name='classroom-update'),
                path('classroom/<str:pk>/delete', ClassroomDeleteView.as_view(),name='classroom-delete'),
                #path('Classroom/<int:pk>/image',ChildImageUpdateView.as_view(),name='Classroom-image'),
                #Subject
                path('subject/new', SubjectCreateView.as_view(),name='subject-create'),
                path('subject_list', SubjectListView.as_view(),name='subject-list'),
                path('subject/<int:pk>/', SubjectDetailView.as_view(),name='subject-detail'),
                path('subject/<int:pk>/update', SubjectUpdateView.as_view(),name='subject-update'),
                path('subject/<int:pk>/delete', SubjectDeleteView.as_view(),name='subject-delete'),
                # Class Members
                path('classmember/new', ClassMemberCreateView.as_view(),name='classmember-create'),
                path('classmember_list', ClassMemberListView.as_view(),name='classmember-list'),
                path('classmember/<str:pk>/', ClassMemberDetailView.as_view(),name='classmember-detail'),
                path('classmember/<str:pk>/update', ClassMemberUpdateView.as_view(),name='classmember-update'),
                path('classmember/<str:pk>/delete', ClassMemberDeleteView.as_view(),name='classmember-delete'),
                # TimeTable
                path('timetable/new', TimetableCreateView.as_view(),name='timetable-create'),
                path('timetable_list', TimetableListView.as_view(),name='timetable-list'),
                path('timetable/<int:pk>/', TimetableDetailView.as_view(),name='timetable-detail'),
                path('timetable/<int:pk>/update', TimetableUpdateView.as_view(),name='timetable-update'),
                path('timetable/<int:pk>/delete', TimetableDeleteView.as_view(),name='timetable-delete'),
                # chatroom
                path('chat/new',chatroom,name='chatroom'),
                path('crud/',CrudView.as_view(), name='crud_ajax'),
               
               ]

app/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.dispatch import receiver
from datetime import datetime
from django.urls import reverse
from django.utils.timezone import now

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

class Student(models.Model):
    """Student models"""
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    # interests = models.OneToOneField(Subject, related_name='mentees', on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.user.username

class Teacher(models.Model):
    """Teacher models"""
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    # interests = models.OneToOneField(Subject, related_name='mentors', on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.user.username

class Classroom(models.Model):
    classname      = models.CharField(max_length=100,primary_key=True)
    class_incharge  = models.CharField(max_length=100, null=True)

    objects         = models.Manager()

    def __str__(self):
        return self.classname
    
    def get_absolute_url(self):
        return reverse("classroom-detail", kwargs={"pk": self.classname})

class Subject(models.Model):
    classname        = models.ForeignKey(Classroom, related_name="Subject1", on_delete=models.CASCADE)
    subject_name     = models.CharField(max_length=100, null=True)
    #subject_incharge = models.CharField(max_length=100, null=True)

    objects         = models.Manager()


    def get_absolute_url(self):
        return reverse("subject-detail", kwargs={"pk": self.pk})
    
    

class ClassMember(models.Model):
    username   = models.CharField(max_length=50,primary_key=True)
    member_id  = models.CharField(max_length=16, null=True)
    classname  = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    subject    = models.CharField(max_length=30)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    objects         = models.Manager()

    def __str__(self):
        return self.username
    
    def get_absolute_url(self):
        return reverse("classmember-detail", kwargs={"pk": self.username})

    
class Timetable(models.Model):
    classname        = models.CharField(max_length=100, null=True)
    subject_name     = models.CharField(max_length=100, null=True)
    day              = models.CharField(max_length=15, null=True)
    start_at         = models.TimeField()
    ends_at          = models.TimeField()
    #subject_incharge = models.CharField(max_length=100, null=True)

    objects         = models.Manager()
    
    def get_absolute_url(self):
        return reverse("timetable-detail", kwargs={"pk": self.pk})


class Chat(models.Model):
    classname        = models.CharField(max_length=100, null=True)
    user_name        = models.CharField(max_length=100, null=True)
    message          = models.TextField(max_length=300, null=True)
    send_at          = models.DateTimeField(auto_now_add=True)

    objects         = models.Manager()

templates/app/classmember_detail.html
{% extends "base.html" %}
{% load static %}
{% block title_content %}
classmember Details|
{% endblock title_content %}
{% block content %}

<h2>classmember<a class="btn btn-large btn-theme margintop10" href = "{% url 'classmember-create' %}" style="float:right"  >Add</a></h2>
<strong> {{classmember.classname|title}}:<br>
Username : </strong> {{classmember.username}} <br>
<strong> Roll No/Employee id :</strong> {{classmember.member_id}}<br>
 <strong> {{classmember.subject}} </strong> 
 Teacher : {{classmember.is_teacher}} <br>
 Student : {{classmember.is_student}} <br>
<a class="btn btn-large btn-theme margintop10" href = "{% url 'classmember-update' classmember.username %}"  > Edit member</a> &nbsp;&nbsp;
<a class="btn btn-large btn-theme margintop10" href = "{% url 'classmember-delete' classmember.username %}"  >Delete </a>
<br/>
{% endblock content %}

templates/app/classmember_form.html
{% extends "base.html" %}

{% block content %}
  <h1> Create classmember </h1>
  <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <p>
      <label for="id_classname"> Class name:</label> 
      <input type="text" name="classname"  maxlength="50" required id="id_classname" >
    </p>
    <p>
      <label for="id_member_id"> Roll no / Employee id:</label> 
      <input type="text" name="member_id"  maxlength="50" required id="id_member_id" >
    </p>
    <p>
      <label for="id_username">Username:</label> 
      <input type="text" name="username" maxlength="50" required id="id_username">
    </p>
    <p>
      <label for="id_subject"> subject:</label>
      <input type="text" name="subject"  maxlength="50" required id="id_subject" >
    </p>
    <p>
      <label for="id_is_teacher">Teacher:</label> 
      <input type="checkbox" name="is_teacher" id="id_is_teacher">
    </p>
    <p>
      <label for="id_is_student">Student:</label>
      <input type="checkbox" name="is_student" id="id_is_student">
    </p>
    
  
    <button class="btn btn-large btn-theme margintop10" type="submit"  >Create class member</button>
  </form>
{% endblock content %}

templates/app/classmember_update_form.html
{% extends "base.html" %}
{% block title_content %}
Class Member details |
{% endblock title_content %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<button class="btn btn-large btn-theme margintop10" type="submit"  >Update details</button>
</form>

{% endblock content %}

templates/app/classroom_confirm_delete.html
{% extends "base.html" %}
{% block title_content %}
Delete Classroom |
{% endblock title_content %}

{% block content %}
<form method = "POST" >
{% csrf_token %}
<h2> Are you sure you want to delete this Classroom </h2>
<strong> {{Classroom.classname|title}} - </strong> 
 by <strong> {{Classroom.class_incharge}} </strong> 
<br/>
<button class="btn btn-large btn-theme margintop10" type="submit"  >Yes, Delete</button>
<a href = "{% url 'classroom-detail' classroom.classname %}"  >cancel</a>
</form>


{% endblock content %}

templates/app/classroom_form.html
{% extends "base.html" %}


{% block content %}
  <h1> Create Classroom </h1>
  <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <p>
      <label for="id_classname"> Class name:</label> 
      <input type="text" name="classname"  maxlength="50" required id="id_classname" >
    </p>
    <p>
      <label for="id_class_incharge">Class incharge:</label> 
      <input type="text" name="class_incharge" value={{user.username}} maxlength="50" required id="id_class_incharge" readonly>
    </p>
  
    <button class="btn btn-large btn-theme margintop10" type="submit"  >Create Classroom</button>
  </form>
{% endblock content %}

templates/app/classroom_list.html
{% extends "base.html" %}
{% block title_content %}
Classroom list |
{% endblock title_content %}
{% block title_script %}
a.button:link, a.button:visited {
  background-color: #001898;
  color: black;
  font-weight: bold;
  padding: 8px 15px;
  margin-bottom :5px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  border-radius: 15px;
}
a.mbutton:link, a.mbutton:visited {
  background-color: black;
  color: white;
  padding: 8px 15px;
  margin-bottom :5px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  border-radius: 15px;
}
a.button:hover, a.button:active {
  background-color: black;
  color: white;
  border-radius: 15px;
}
{% endblock title_script %}
{% block content %}
<h2> Classrooms List </h2>
<div class="w3-hide-small">
    {% if user.is_teacher or user.is_staff %}
        <a class="button" href = "{% url 'classroom-create' %}" style="margin-top:-47px;float:right"  >Create classroom </a>
        <br><br>
    {%endif%}
    {% for classroom in classrooms %}
      
        {% if user.is_teacher or user.is_staff %}

            <strong> {{classroom.classname}}</strong> 
            by <strong> {{classroom.class_incharge}} </strong> 
            <a class="button" href ="{% url 'classroom-detail' classroom.classname %}"  > Open Classroom </a>
            <br>
        {% endif %}
        {% if classroom.class_incharge == user.username %}
            <a href = "{% url 'classroom-update' classroom.classname %}"  > Update Classroom </a>
            &nbsp;&nbsp;&nbsp;<a  href = "{% url 'classroom-delete' classroom.classname %}" >Delete </a>
        {% endif %}
      
    {% endfor %}
</div>


{% endblock content %}

templates/app/subject_detail.html
{% extends "base.html" %}
{% load static %}
{% block title_content %}
subject Details|
{% endblock title_content %}
{% block content %}

<h2>subject<a class="btn btn-large btn-theme margintop10" href = "{% url 'subject-create' %}" style="float:right"  >Add</a></h2>
<strong> Class Name : </strong>{{subject.classname|title}}:<br>
 <strong> Subject Name{{subject.subject}} </strong> 
<a class="btn btn-large btn-theme margintop10" href = "{% url 'subject-update' subject.id %}"  > Edit subject</a> &nbsp;&nbsp;
<a class="btn btn-large btn-theme margintop10" href = "{% url 'subject-delete' subject.id %}"  >Delete </a>
<br/>
{% endblock content %}

templates/app/subject_form.html
{% extends "base.html" %}

{% block content %}
  <h1> Add Subject </h1>
  <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <p>
      <label for="id_classname"> Class name:</label> 
      <input type="text" name="classname"  maxlength="50" required id="id_classname" >
    </p>
    <p>
      <label for="id_subject_name"> subject name:</label>
      <input type="text" name="subject_name"  maxlength="50" required id="id_subject_name" >
    </p>
  
    <button class="btn btn-large btn-theme margintop10" type="submit"  >Add Subject</button>
  </form>
{% endblock content %}

templates/app/subject_list.html
{% extends "base.html" %}
{% block title_content %}
Subjects list |
{% endblock title_content %}

{% block content %}
<h2> Subjects List <a class="btn btn-large btn-theme margintop10" href = "{% url 'subject-create' %}" style="float:right"  >Add subject </a></h2>
<table>
<tr>
<th><strong> Subjects: </strong></th>
<th><strong> Classroom: </strong></th>
</tr>
{% for subject in subjects %}
<tr>
<td> <a href = "{% url 'subject-detail' subject.id %}" >{{subject.subject_name}} </a></td>
<td>{{subject.classname}}</td>
</tr>
{% endfor %}
</table>

{% endblock content %}

templates/app/subject_update_form.html
{% extends "base.html" %}
{% block title_content %}
Update Subject|
{% endblock title_content %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<button class="btn btn-large btn-theme margintop10" type="submit"  >Update details</button>
</form>

{% endblock content %}

templates/app/timetable_confirm_delete.html
{% extends "base.html" %}
{% block title_content %}
Delete classmember |
{% endblock title_content %}

{% block content %}
<form method = "POST" >
{% csrf_token %}
<h2> Are you sure you want to delete this classmember </h2>
<strong> {{classmember.classname|title}} - </strong> 
 by <strong> {{classmember.username}} </strong> 
<br/>
<button class="btn btn-large btn-theme margintop10" type="submit"  >Yes, Delete</button>
<a class="btn btn-large btn-theme margintop10" href = "{% url 'classmember-detail' classmember.username %}"  >cancel</a>
</form>


{% endblock content %}

templates/app/timetable_detail.html
{% extends "base.html" %}
{% load static %}
{% block title_content %}
timetable Details|
{% endblock title_content %}
{% block content %}
<br>
<h2>Timetable<a class="btn btn-large btn-theme margintop10" href = "{% url 'timetable-create' %}" style="float:right"  >Add</a></h2>
<strong> {{timetable.classname|title}}:<br>
 Subject : {{timetable.subject_name}}<br>
 Starts at : {{timetable.start_at}} <br>
 Ends at : {{timetable.ends_at}} <br>
<a class="btn btn-large btn-theme margintop10" href = "{% url 'timetable-update' timetable.id %}"  > Edit member</a> &nbsp;&nbsp;
<a class="btn btn-large btn-theme margintop10" href = "{% url 'timetable-delete' timetable.id %}"  >Delete </a>
<br/>
{% endblock content %}

templates/app/timetable_form.html
{% extends "base.html" %}

{% block content %}
  <h1> Add  </h1>
  <form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <p>
      <label for="id_classname"> Class name:</label> 
      <input type="text" name="classname"  maxlength="50" required id="id_classname" >
    </p>
    <p>
      <label for="id_subject_name"> subject_name:</label> 
      <input type="text" name="subject_name"  maxlength="50" required id="id_subject_name" >
    </p>
    <p>
      <label for="id_day">day:</label> 
      <input type="text" name="day" maxlength="50" required id="id_day">
    </p>
    <p>
      <label for="id_start_at"> start_at:</label>
      <input type="time" name="start_at"  maxlength="50" required id="id_start_at" >
    </p>
    <p>
      <label for="id_ends_at"> ends_at:</label>
      <input type="time" name="ends_at"  maxlength="50" required id="id_ends_at" >
    </p>
  
    <button class="btn btn-large btn-theme margintop10" type="submit"  >Add in timetable</button>
  </form>
{% endblock content %}

templates/app/timetable_update_form.html
{% extends "base.html" %}
{% block title_content %}
Timetable Update |
{% endblock title_content %}

{% block content %}
<br>
<h2>Timetable Update </h2>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<button class="btn btn-large btn-theme margintop10" type="submit"  >Update details</button>
</form>

{% endblock content %}